# Default values for zookeeper.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
Image: armdocker.rnd.ericsson.se/aia_releases/zookeeper
ImageTag: v3.4.9
Servers: 3
Cpu: "1"
Memory: "4Gi"
Heap: "2G"
Storage: "5Gi"
#StorageClass : default
ServerPort: 2888
LeaderElectionPort: 3888
ClientPort: 2181
ImagePullPolicy: "Always"
TickTimeMs: 2000
InitTicks: 10
SyncTicks: 5
ClientCnxns: 60
SnapRetain: 3
PurgeHours: 1
ProbeInitialDelaySeconds : 15
ProbeTimeoutSeconds : 5
AntiAffinity : "hard"
LogLevel : "INFO"
